In [1]:
import mlflow


mlflow.set_tracking_uri("sqlite:///mlflow.db")
mlflow.set_experiment("spam-experiment")

<Experiment: artifact_location='/mnt/c/Users/user/Documents/Projects/mlops-exer-1/notebooks/mlruns/1', creation_time=1780963326545, effective_trace_archival_retention=None, experiment_id='1', last_update_time=1780963326545, lifecycle_stage='active', name='spam-experiment', tags={}, trace_location=None, workspace='default'>

In [2]:
# from spam_checker.data.spam_data_module import SPAMDataModule

In [3]:
# spam_data = SPAMDataModule()

In [4]:
# spam_data.prepare_data()

In [5]:
import pandas as pd

# Paste your copied file path inside the quotes
# df = pd.read_csv('../test_dataset/spam.csv')

df = pd.read_csv('../test_dataset/spam.csv', encoding_errors='ignore')

df = df[['v1', 'v2']]

# df['v1'] = df['v1'].replace('spam', '1')
# df['v1'] = df['v1'].replace('ham', '0')
df = df.rename(columns={"v1": "label", "v2": "text"})

# View the first few rows of your data
df.head(10)

  label                                               text
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...
5  spam  FreeMsg Hey there darling it's been 3 week's n...
6   ham  Even my brother is not like to speak with me. ...
7   ham  As per your request 'Melle Melle (Oru Minnamin...
8  spam  WINNER!! As a valued network customer you have...
9  spam  Had your mobile 11 months or more? U R entitle...

In [6]:
# df['label'] = df['label'].replace('spam', '1')
# df['label'] = df['label'].replace('ham', '0')

# # View the first few rows of your data
# df.head(10)

In [7]:
len(df.index)

5572

In [8]:
empty_spam_rows = df[df['text'].isna()]
print(empty_spam_rows)

Empty DataFrame
Columns: [label, text]
Index: []

In [9]:
empty_count = df['text'].isna().sum()
print(f"Empty cells: {empty_count}")

Empty cells: 0

In [10]:
!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 12.2 MB/s  0:00:01m0:00:0100:01
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

In [11]:
import spacy

nlp = spacy.load("en_core_web_sm")

In [12]:
doc = nlp("spaCy is successfully working in Jupyter!")
for token in doc:
    print(token.text, token.pos_)

spaCy NUM
is AUX
successfully ADV
working VERB
in ADP
Jupyter PROPN
! PUNCT

In [13]:
# Function to clean the text
def clean_text(text):
    doc = nlp(text)  # Process the text with spaCy
    cleaned_tokens = []
    for token in doc:
        # Remove stop words, punctuation, and retain only alphabetic words
        if not token.is_stop and not token.is_punct and token.is_alpha:
            cleaned_tokens.append(token.lemma_)  # Append the lemmatized version of the token
    return " ".join(cleaned_tokens)

# Apply the cleaning function to the 'text' column in the dataset
# df['cleaned_text'] = df['text'].apply(clean_text)

In [14]:
df.head(10)

  label                                               text
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...
5  spam  FreeMsg Hey there darling it's been 3 week's n...
6   ham  Even my brother is not like to speak with me. ...
7   ham  As per your request 'Melle Melle (Oru Minnamin...
8  spam  WINNER!! As a valued network customer you have...
9  spam  Had your mobile 11 months or more? U R entitle...

In [15]:
training_input_labels = df.loc[:, df.columns == 'label']
training_input_text = df.loc[:, df.columns != 'label']

print(training_input_labels['label'].value_counts())

label
ham     4825
spam     747
Name: count, dtype: int64

In [16]:
print(training_input_labels)

     label
0      ham
1      ham
2     spam
3      ham
4      ham
...    ...
5567  spam
5568   ham
5569   ham
5570   ham
5571   ham

[5572 rows x 1 columns]

In [17]:
from sklearn.model_selection import train_test_split

train_text_temp, val_text_final, train_labels_temp, val_labels = train_test_split(
    training_input_text, training_input_labels, train_size=0.5, random_state=0, stratify=training_input_labels)

train_text_final, test_text_final, train_labels, test_labels = train_test_split(
    train_text_temp, train_labels_temp, train_size=0.8, random_state=0, stratify=train_labels_temp)

In [18]:
train_text_combined = pd.concat([train_labels, train_text_final], axis=1).reset_index(drop=True)

In [19]:
test_text_combined = pd.concat([test_labels, test_text_final], axis=1).reset_index(drop=True)

In [20]:
val_text_combined = pd.concat([val_labels, val_text_final], axis=1).reset_index(drop=True)

In [21]:
empty_spam_rows = train_text_combined[train_text_combined['text'].isna()]
print(empty_spam_rows)

Empty DataFrame
Columns: [label, text]
Index: []

In [22]:
# empty_spam_rows = train_text_combined[train_text_combined['cleaned_text'].isna()]
# print(empty_spam_rows)

In [23]:
empty_spam_rows = train_text_combined[train_text_combined['label'].isna()]
print(empty_spam_rows)

Empty DataFrame
Columns: [label, text]
Index: []

In [24]:
def spacy_tokenizer(text):
    # Use the clean_lemm function first
    cleaned_text = clean_text(text)
    # Then tokenize the cleaned text
    return cleaned_text.split()

In [25]:
from collections import defaultdict

def build_vocab(text_iterator, min_freq=3, specials=('<unk>', '<pad>')):
    token_counts = defaultdict(int)
    for text in text_iterator:
        for token in spacy_tokenizer(text):
            token_counts[token] += 1
    vocab = {token: idx for idx, (token, count) in enumerate(token_counts.items()) if count >= min_freq}
    for special in specials:
        if special not in vocab:
            vocab[special] = len(vocab) 
    return vocab
vocab = build_vocab(df['text'])
# vocab = build_vocab(df['cleaned_text'])
vocab_size = len(vocab)

In [26]:
print(vocab_size)

2216

In [27]:
print(vocab)

{'point': 1, 'crazy': 2, 'available': 3, 'bugis': 4, 'n': 5, 'great': 6, 'world': 7, 'la': 8, 'e': 9, 'get': 12, 'wat': 14, 'ok': 15, 'lar': 16, 'joke': 17, 'wif': 18, 'u': 19, 'oni': 20, 'free': 21, 'entry': 22, 'wkly': 23, 'comp': 24, 'win': 25, 'Cup': 27, 'final': 28, 'tkts': 29, 'text': 30, 'receive': 32, 'txt': 33, 'apply': 34, 'dun': 35, 'early': 36, 'c': 38, 'Nah': 39, 'think': 40, 'go': 41, 'usf': 42, 'live': 43, 'FreeMsg': 44, 'hey': 45, 'week': 47, 'word': 48, 'like': 49, 'fun': 50, 'tb': 51, 'std': 53, 'send': 55, 'brother': 57, 'speak': 58, 'treat': 59, 'request': 62, 'Melle': 63, 'Oru': 64, 'Minnaminunginte': 65, 'Nurungu': 66, 'Vettam': 67, 'set': 68, 'callertune': 69, 'Callers': 70, 'press': 71, 'copy': 72, 'friend': 73, 'Callertune': 74, 'WINNER': 75, 'value': 76, 'network': 77, 'customer': 78, 'select': 79, 'prize': 81, 'reward': 82, 'claim': 83, 'code': 84, 'valid': 85, 'hour': 86, 'mobile': 87, 'month': 88, 'U': 89, 'R': 90, 'entitle': 91, 'update': 92, 'late': 93, 'colour': 94, 'camera': 95, 'Mobile': 96, 'Update': 97, 'Co': 98, 'to': 99, 'home': 100, 'soon': 101, 'want': 102, 'talk': 103, 'stuff': 104, 'anymore': 105, 'tonight': 106, 'k': 107, 'cry': 108, 'today': 109, 'chance': 110, 'cash': 111, 'pound': 112, 'Cost': 113, 'day': 114, 'Reply': 116, 'HL': 117, 'info': 118, 'URGENT': 119, 'membership': 120, 'Prize': 121, 'POBOX': 124, 'search': 125, 'right': 126, 'thank': 127, 'promise': 129, 'will': 130, 'not': 131, 'help': 132, 'wonderful': 135, 'blessing': 136, 'time': 137, 'date': 138, 'use': 141, 'credit': 142, 'click': 143, 'WAP': 144, 'link': 145, 'message': 146, 'oh': 147, 'watch': 148, 'eh': 149, 'remember': 150, 'spell': 151, 'yes': 152, 'v': 153, 'naughty': 154, 'wet': 155, 'fine': 156, 's': 157, 'way': 158, 'feel': 159, 'b': 161, 'England': 162, 'miss': 164, 'goal': 165, 'team': 166, 'news': 167, 'ur': 168, 'national': 169, 'eg': 170, 'ENGLAND': 171, 'try': 172, 'WALES': 173, 'seriously': 175, 'm': 176, 'ha': 177, 'pay': 178, 'da': 179, 'stock': 180, 'comin': 181, 'aft': 182, 'finish': 183, 'lunch': 184, 'str': 185, 'lor': 186, 'ard': 187, 'smth': 188, 'alright': 190, 'meet': 191, 'force': 192, 'eat': 193, 'slice': 194, 'hungry': 195, 'tho': 196, 'suck': 197, 'Mark': 198, 'worried': 199, 'know': 200, 'sick': 201, 'turn': 202, 'pizza': 203, 'lol': 204, 'catch': 206, 'bus': 207, 'fry': 208, 'egg': 209, 'tea': 210, 'mom': 211, 'leave': 212, 'dinner': 213, 'Love': 214, 'amp': 215, 'pack': 216, 'car': 217, 'let': 218, 'room': 219, 'work': 221, 'wait': 223, 'clear': 224, 'sure': 225, 'x': 227, 'yeah': 228, 'fall': 230, 'child': 233, 'till': 234, 'cheer': 236, 'K': 237, 'tell': 238, 'fear': 239, 'subscription': 244, 'Ringtone': 245, 'UK': 246, 'charge': 247, 'confirm': 248, 'reply': 249, 'yup': 250, 'look': 251, 'timing': 252, 'msg': 253, 'learn': 255, 'lesson': 256, 'oops': 257, 'roommate': 258, 'letter': 259, 'decide': 260, 'hello': 261, 'saturday': 262, 'texte': 263, 'tomo': 264, 'invite': 265, 'pls': 266, 'ahead': 267, 'weekend': 269, 'Abiola': 270, 'forget': 271, 'need': 272, 'crave': 273, 'love': 274, 'sweet': 275, 'yummy': 279, 'MSG': 282, 'sms': 283, 'nokia': 284, 'camcorder': 285, 'delivery': 286, 'tomorrow': 287, 'see': 288, 'hope': 289, 'man': 290, 'inch': 292, 'call': 293, 'nigeria': 296, 'fair': 297, 'hopefully': 298, 'tyler': 299, 'maybe': 300, 'ask': 301, 'bit': 302, 'hospital': 304, 'keep': 305, 'weak': 306, 'class': 308, 'gram': 309, 'usually': 310, 'run': 311, 'half': 312, 'smart': 314, 'second': 315, 'fyi': 316, 'ride': 317, 'morning': 318, 'crash': 319, 'place': 320, 'wow': 321, 'realize': 322, 'embarasse': 323, 'good': 325, 'happy': 326, 'sorry': 327, 'offer': 328, 'SMS': 330, 'ac': 331, 'New': 333, 'play': 339, 'correct': 342, 'end': 344, 'END': 345, 'yesterday': 349, 'find': 350, 'Congrats': 351, 'year': 352, 'special': 353, 'cinema': 354, 'pass': 355, 'Suprman': 356, 'V': 357, 'etc': 358, 'later': 359, 'meeting': 360, 'reach': 361, 'series': 365, 'pick': 366, 'pain': 368, 'kill': 369, 'girl': 370, 'situation': 371, 'check': 373, 'IQ': 374, 'take': 375, 'forever': 376, 'come': 377, 'double': 378, 'hair': 379, 'dresser': 380, 'say': 381, 'wun': 382, 'cut': 383, 'short': 384, 'nice': 385, 'pleased': 386, 'advise': 387, 'follow': 388, 'recent': 389, 'review': 390, 'Mob': 391, 'award': 392, 'Bonus': 393, 'song': 395, 'valuable': 397, 'frnd': 398, 'rply': 399, 'Urgent': 400, 'UR': 401, 'complimentary': 402, 'trip': 403, 'hear': 407, 'new': 408, 'plane': 410, 'lucky': 412, 'save': 413, 'money': 414, 'Hee': 415, 'HI': 417, 'babe': 418, 'IM': 419, 'WANNA': 421, 'XX': 422, 'machan': 424, 'cool': 425, 'gentleman': 426, 'dignity': 427, 'respect': 428, 'people': 429, 'pa': 431, 'job': 433, 'Ta': 434, 'earn': 435, 'ah': 436, 'hi': 437, 'stop': 438, 'urgnt': 439, 'sm': 440, 'real': 441, 'yo': 442, 'ticket': 443, 'start': 446, 'bed': 447, 'coin': 448, 'nitro': 450, 'kano': 452, 'download': 453, 'wen': 454, 'stand': 455, 'close': 456, 'll': 457, 'night': 458, 'spend': 459, 'afternoon': 460, 'mean': 462, 'y': 463, 'include': 464, 'sheet': 465, 'smile': 466, 'Smile': 468, 'trouble': 470, 'pour': 471, 'rain': 472, 'hurt': 473, 'becoz': 474, 'service': 475, 'representative': 476, 'WON': 477, 'guarantee': 478, 'plan': 479, 'buy': 480, 'lido': 481, 'ringtone': 482, 'collect': 483, 'simply': 484, 'password': 485, 'verify': 486, 'movie': 491, 'abt': 492, 'load': 493, 'loan': 494, 'hol': 496, 'forgot': 497, 'appointment': 499, 'shower': 500, 'cause': 501, 'prob': 502, 'ham': 503, 'okay': 504, 'price': 505, 'long': 506, 'legal': 507, 'Wen': 508, 'Y': 509, 'ave': 510, 'xx': 512, 'drive': 513, 'test': 514, 'guess': 515, 'give': 516, 'boston': 517, 'change': 518, 'location': 519, 'nyc': 520, 'cuz': 521, 'page': 523, 'umma': 524, 'life': 525, 'vava': 526, 'lot': 527, 'dear': 528, 'wish': 529, 'birthday': 530, 'make': 531, 'truly': 532, 'Aight': 534, 'hit': 535, 'address': 537, 'consider': 538, 'computer': 539, 'old': 543, 'well': 544, 'lie': 545, 'worry': 546, 'busy': 547, 'research': 550, 'cos': 551, 'thing': 552, 'mah': 554, 'loud': 555, 'contact': 557, 'draw': 558, 'show': 559, 'Code': 560, 'wa': 561, 'sentence': 563, 'juz': 565, 'tt': 566, 'eatin': 567, 'weight': 569, 'haha': 570, 'anythin': 571, 'happen': 572, 'enter': 573, 'cabin': 574, 'PA': 575, 'Happy': 576, 'Boss': 577, 'askd': 578, 'apartment': 579, 'winner': 580, 'specially': 581, 'holiday': 582, 'flights': 583, 'inc': 584, 'operator': 585, 'min': 586, 'friday': 588, 'Hmm': 592, 'uncle': 593, 'inform': 594, 'school': 595, 'directly': 596, 'food': 597, 'private': 598, 'Account': 599, 'Statement': 600, 'unredeemed': 601, 'Points': 602, 'Identifier': 603, 'expire': 604, 'Caller': 605, 'Landline': 606, 'Voda': 608, 'number': 609, 'match': 610, 'quote': 611, 'standard': 612, 'rate': 613, 'app': 614, 'mu': 616, 'bother': 619, 'apologise': 622, 'HEY': 623, 'GIRL': 624, 'r': 625, 'HOPE': 626, 'BAK': 628, 'cost': 631, 'answer': 633, 'question': 634, 'Sunshine': 635, 'Quiz': 636, 'Wkly': 637, 'Q': 638, 'Sony': 639, 'dvd': 640, 'player': 641, 'country': 642, 'ansr': 644, 'sp': 645, 'tyrone': 646, 'lay': 647, 'dogging': 648, 'direct': 649, 'mob': 650, 'join': 651, 'large': 652, 'dog': 653, 'Network': 654, 'bt': 655, 'txte': 656, 'haf': 659, 'befor': 661, 'activity': 662, 'chat': 663, 'yr': 667, 'Got': 668, 'lazy': 669, 'type': 670, 'lect': 671, 'Sir': 673, 'mail': 674, 'swt': 675, 'thought': 676, 'tired': 677, 'little': 678, 'lovable': 679, 'person': 680, 'Coz': 681, 'occupy': 683, 'd': 684, 'big': 685, 'gud': 687, 'open': 688, 'ya': 689, 'sexy': 693, 'female': 694, 'local': 695, 'Luv': 696, 'Netcollex': 697, 'Ltd': 698, 'begin': 699, 'qatar': 700, 'pray': 701, 'hard': 702, 'delete': 703, 'birla': 705, 'soft': 706, 'wine': 707, 'flow': 708, 'thk': 710, 'cine': 711, 'floor': 715, 'window': 716, 'shirt': 717, 'dream': 720, 'joy': 722, 'tv': 723, 'house': 728, 'interview': 729, 'boy': 730, 'Years': 732, 'arrange': 733, 'safe': 734, 'hand': 736, 'F': 739, 'FRND': 740, 'order': 742, 'Service': 743, 'Msg': 744, 'content': 745, 'wap': 747, 'internet': 749, 'menu': 750, 'module': 752, 'Claim': 753, 'avoid': 754, 'wit': 756, 'escape': 758, 'fancy': 759, 'completely': 762, 'utter': 763, 'waste': 764, 'account': 767, 'bank': 768, 'Hmmm': 769, 'Thk': 770, 'hop': 771, 'muz': 772, 'discuss': 773, 'liao': 774, 'bloody': 775, 'hell': 776, 'believe': 777, 'Ill': 780, 'spanish': 782, 'bath': 783, 'carlos': 784, 'stay': 786, 'til': 787, 'smoke': 788, 'worth': 789, 'log': 790, 'MANEESHA': 791, 'satisfied': 792, 'experience': 793, 'Toll': 794, 'Free': 795, 'lift': 796, 'especially': 797, 'trust': 801, 'guy': 802, 'net': 804, 'mummy': 805, 'boytoy': 806, 'Haha': 807, 'awesome': 808, 'minute': 809, 'freephone': 810, 'Xmas': 811, 'radio': 812, 'jus': 813, 'bathe': 814, 'sis': 815, 'unique': 816, 'touch': 819, 'deal': 820, 'personal': 821, 'finally': 822, 'complete': 823, 'course': 824, 'suggest': 825, 'able': 826, 'settle': 829, 'mrng': 831, 'hav': 832, 'story': 833, 'dead': 835, 'tmr': 836, 'pm': 837, 'orchard': 838, 'mrt': 839, 'Kate': 840, 'evening': 841, 'xxx': 843, 'buck': 845, 'darlin': 846, 've': 847, 'college': 848, 'successfully': 850, 'balance': 854, 'Transaction': 855, 'ID': 856, 'Goodmorning': 858, 'sleep': 859, 'dat': 862, 'oso': 864, 'oredi': 865, 'aight': 866, 'straight': 867, 'connection': 869, 'bill': 871, 'shoot': 872, 'ready': 873, 'break': 875, 'semester': 877, 'noe': 878, 'leh': 879, 'sound': 880, 'head': 881, 'past': 883, 'exam': 885, 'march': 886, 'gt': 887, 'atm': 888, 'register': 889, 'important': 894, 'file': 895, 'system': 896, 'repair': 897, 'shop': 898, 'nite': 900, 'Mobiles': 902, 'NOKIA': 903, 'appreciate': 904, 'partner': 905, 'career': 906, 'star': 909, 'sign': 910, 'company': 912, 'po': 914, 'Bcoz': 918, 'teach': 920, 'walk': 925, 'cross': 926, 'road': 927, 'street': 928, 'battery': 930, 'die': 931, 'flirt': 932, 'AGE': 934, 'print': 937, 'ill': 939, 'wil': 940, 'theory': 941, 'Argument': 942, 'SITUATION': 943, 'lose': 944, 'argue': 945, 'kick': 946, 'secret': 947, 'admirer': 948, 'laptop': 951, 'case': 952, 'avent': 955, 'face': 959, 'fr': 960, 'Thanx': 961, 'website': 963, 'slipper': 964, 'bat': 966, 'innings': 967, 'fix': 969, 'wake': 970, 'dearly': 971, 'congratulation': 972, 'cd': 973, 'voucher': 974, 'music': 975, 'TnCs': 976, 'www': 977, 'Ranjith': 978, 'cal': 979, 'hold': 983, 'bcum': 984, 'angry': 985, 'wid': 986, 'dnt': 987, 'childish': 988, 'true': 989, 'deep': 990, 'affection': 991, 'care': 992, 'luv': 993, 'kettoda': 994, 'manda': 995, 'ship': 997, 'lemme': 1002, 'expect': 1004, 'lover': 1009, 'Video': 1010, 'anytime': 1012, 'unlimited': 1013, 'TEXT': 1014, 'park': 1015, 'mini': 1016, 'Dun': 1017, 'disturb': 1018, 'ring': 1020, 'horny': 1022, 'naked': 1023, 'hot': 1024, 'unsubscribe': 1025, 'dint': 1026, 'choose': 1029, 'wk': 1031, 'PO': 1032, 'flash': 1034, 'jealous': 1035, 'Club': 1036, 'single': 1037, 'quality': 1039, 'sort': 1040, 'sunny': 1042, 'ray': 1043, 'blue': 1044, 'bay': 1045, 'HMV': 1046, 'BONUS': 1047, 'SPECIAL': 1048, 'genuine': 1049, 'easy': 1050, 'bf': 1053, 'thanx': 1054, 'Awesome': 1059, 'celebration': 1060, 'swing': 1061, 'far': 1063, 'okie': 1064, 'usual': 1065, 'anybody': 1067, 'throw': 1068, 'baby': 1069, 'fone': 1071, 'shall': 1073, 'sense': 1076, 'gautham': 1077, 'stupid': 1079, 'cam': 1080, 'buzy': 1081, 'accidentally': 1082, 'T': 1084, 'CAMERA': 1085, 'phone': 1086, 'upgrade': 1087, 'sim': 1088, 'card': 1089, 'loyalty': 1090, 'tease': 1093, 'plz': 1094, 'rise': 1095, 'STUPID': 1097, 'BSLVYL': 1098, 'coffee': 1099, 'somebody': 1100, 'high': 1101, 'shit': 1103, 'imagine': 1106, 'meal': 1110, 'book': 1123, 'wana': 1125, 'friendship': 1126, 'hang': 1127, 'themob': 1129, 'selection': 1130, 'Games': 1131, 'Tones': 1132, 'sport': 1134, 'fit': 1135, 'garage': 1137, 'key': 1138, 'ACCEPT': 1140, 'DAY': 1141, 'accept': 1142, 'Brother': 1143, 'Sister': 1144, 'Lover': 1145, 'Lvblefrnd': 1146, 'Jstfrnd': 1147, 'Cutefrnd': 1148, 'Lifpartnr': 1149, 'Belovd': 1150, 'Swtheart': 1151, 'Bstfrnd': 1152, 'enemy': 1153, 'weekly': 1154, 'quiz': 1155, 'BOX': 1157, 'definitely': 1158, 'normal': 1159, 'rest': 1160, 'Hope': 1162, 'wot': 1163, 'pongal': 1164, 'kb': 1165, 'power': 1166, 'yoga': 1167, 'dunno': 1168, 'dude': 1172, 'afraid': 1173, 'December': 1174, 'cake': 1175, 'Merry': 1176, 'Christmas': 1177, 'kiss': 1178, 'cud': 1179, 'ppl': 1180, 'gona': 1181, 'waitin': 1183, 'flight': 1187, 'problem': 1188, 'track': 1190, 'record': 1191, 'read': 1192, 'woman': 1193, 'light': 1194, 'return': 1195, 'immediately': 1196, 'Germany': 1197, 'line': 1199, 'access': 1200, 'steal': 1205, 'report': 1208, 'supervisor': 1209, 'Valentines': 1210, 'Day': 1211, 'lifetime': 1213, 'rcvd': 1214, 'din': 1216, 'surf': 1217, 'post': 1218, 'wiv': 1220, 'favourite': 1222, 'hide': 1224, 'strange': 1225, 'interested': 1226, 'sister': 1227, 'round': 1228, 'Gudnite': 1229, 'tc': 1230, 'practice': 1231, 'yijue': 1233, 'num': 1235, 'small': 1236, 'shag': 1238, 'Txts': 1241, 'slap': 1249, 'fault': 1251, 'basically': 1252, 'Yo': 1253, 'figure': 1254, 'alcohol': 1255, 'Jay': 1256, 'weed': 1258, 'insurance': 1265, 'Qatar': 1266, 'Rakhesh': 1269, 'ex': 1270, 'currently': 1275, 'maximize': 1276, 'HG': 1278, 'row': 1279, 'moment': 1281, 'st': 1282, 'cold': 1284, 'chikku': 1285, 'forward': 1288, 'breathe': 1293, 'air': 1294, 'Offer': 1296, 'Motorola': 1297, 'SonyEricsson': 1298, 'Nokia': 1299, 'FREE': 1300, 'Bluetooth': 1301, 'Double': 1302, 'Mins': 1303, 'Txt': 1304, 'Orange': 1305, 'discount': 1306, 'Customer': 1307, 'Wat': 1309, 'geeee': 1311, 'cuddle': 1312, 'spoil': 1313, 'willing': 1315, 'Order': 1316, 'recognise': 1319, 'sigh': 1322, 'bar': 1323, 'Ptbo': 1324, 'bring': 1328, 'sir': 1329, 'project': 1331, 'mistake': 1333, 'body': 1334, 'slow': 1335, 'guide': 1336, 'relax': 1338, 'reason': 1339, 'couple': 1341, 'txts': 1343, 'lick': 1345, 'mm': 1346, 'rental': 1347, 'MobilesDirect': 1348, 'have': 1349, 'huh': 1350, 'sit': 1351, 'intro': 1352, 'pilate': 1353, 'Morning': 1355, 'office': 1356, 'shut': 1358, 'bout': 1359, 'current': 1362, 'period': 1363, 'actually': 1364, 'rock': 1365, 'put': 1366, 'business': 1367, 'picture': 1368, 'ass': 1369, 'facebook': 1370, 'God': 1374, 'India': 1377, 'quickly': 1379, 'wanna': 1380, 'poly': 1382, 'tone': 1383, 'chechi': 1384, 'cream': 1385, 'Yep': 1386, 'xmas': 1388, 'tree': 1389, 'burn': 1390, 'darling': 1395, 'Fancy': 1397, 'drink': 1398, 'sender': 1401, 'yan': 1404, 'jiu': 1405, 'den': 1407, 'blah': 1408, 'competition': 1411, 'WIN': 1412, 'logo': 1413, 'name': 1414, 'heart': 1415, 'LOVE': 1417, 'EVE': 1419, 'ad': 1422, 'landline': 1423, 'hostel': 1425, 'land': 1426, 'voice': 1427, 'aathi': 1430, 'esplanade': 1432, 'mind': 1433, 'wnt': 1434, 'BMW': 1435, 'urgently': 1436, 'vry': 1437, 'hv': 1438, 'shortage': 1439, 'source': 1440, 'arng': 1441, 'dis': 1442, 'amt': 1443, 'lac': 1444, 'that': 1445, 'fucking': 1446, 'respond': 1447, 'video': 1448, 'Calls': 1449, 'vary': 1451, 'Ldn': 1452, 'th': 1455, 'askin': 1456, 'dollar': 1457, 'g': 1459, 'iouri': 1460, 'fuck': 1462, 'journey': 1463, 'gd': 1464, 'kallis': 1466, 'cricket': 1467, 'tough': 1469, 'suppose': 1470, 'Oic': 1471, 'tot': 1472, 'group': 1473, 'kinda': 1481, 'hmm': 1482, 'LOL': 1484, 'detail': 1487, 'improve': 1489, 'purpose': 1490, 'homeowner': 1491, 'tenant': 1492, 'welcome': 1493, 'previously': 1494, 'refuse': 1495, 'si': 1496, 'beautiful': 1501, 'intelligent': 1502, 'dont': 1504, 'result': 1506, 'kind': 1508, 'ear': 1510, 'ttyl': 1511, 'bad': 1512, 'Miss': 1513, 'different': 1514, 'decision': 1515, 'cop': 1516, 'opt': 1520, 'bye': 1521, 'railway': 1522, 'princess': 1523, 'doggy': 1525, 'style': 1526, 'fave': 1527, 'position': 1528, 'enjoy': 1529, 'Dear': 1534, 'Dave': 1535, 'notice': 1536, 'Tenerife': 1537, 'Holiday': 1538, 'SAE': 1539, 'scream': 1540, 'remove': 1541, 'flat': 1542, 'transfer': 1543, 'cum': 1547, 'wise': 1549, 't': 1550, 'sec': 1553, 'fb': 1555, 'Activate': 1560, 'Messages': 1561, 'term': 1562, 'condition': 1563, 'visit': 1564, 'depend': 1565, 'boye': 1566, 'dry': 1570, 'meh': 1573, 'nope': 1574, 'monday': 1575, 'center': 1579, 'fight': 1581, 'fightng': 1582, 'dificult': 1583, 'fish': 1586, 'water': 1587, 'bored': 1589, 'outside': 1590, 'village': 1593, 'near': 1594, 'fee': 1596, 'rent': 1597, 'opinion': 1599, 'Jada': 1600, 'Kusruthi': 1601, 'silent': 1602, 'Spl': 1603, 'character': 1604, 'mature': 1605, 'stylish': 1606, 'simple': 1607, 'Pls': 1608, 'Prabha': 1612, 'soryda': 1613, 'realy': 1614, 'frm': 1615, 'sory': 1616, 'forgive': 1617, 'jst': 1618, 'tat': 1619, 'Phone': 1620, 'GB': 1621, 'iPod': 1622, 'IBHltd': 1623, 'POLY': 1625, 'sat': 1638, 'bday': 1639, 'fri': 1642, 'adult': 1644, 'behave': 1645, 'rude': 1650, 'campus': 1651, 'attempt': 1652, 'christmas': 1653, 'SavaMob': 1655, 'member': 1656, 'Sub': 1657, 'Unsub': 1658, 'pretty': 1659, 'lady': 1660, 'un': 1666, 'redeem': 1667, 'sunday': 1668, 'malaria': 1669, 'lead': 1671, 'passionate': 1672, 'sea': 1673, 'probably': 1674, 'lt': 1675, 'fat': 1676, 'finger': 1677, 'Ummmmmaah': 1679, 'HAPPY': 1680, 'BIRTHDAY': 1681, 'tirupur': 1682, 'develop': 1685, 'listen': 1687, 'self': 1690, 'marry': 1692, 'hotel': 1697, 'english': 1700, 'omw': 1703, 'btw': 1704, 'cock': 1709, 'remind': 1711, 'own': 1712, 'hurry': 1714, 'generally': 1719, 'blood': 1722, 'warm': 1725, 'cup': 1726, 'milk': 1727, 'loose': 1729, 'cheap': 1731, 'likely': 1733, 'essential': 1737, 'pic': 1739, 'Aiyo': 1740, 'fast': 1743, 'workin': 1744, 'barely': 1750, 'gym': 1760, 'daddy': 1761, 'pleasure': 1762, 'Yar': 1765, 'mum': 1766, 'sch': 1767, 'clean': 1768, 'lab': 1769, 'door': 1771, 'marriage': 1773, 'snake': 1776, 'bite': 1777, 'dance': 1778, 'izzit': 1782, 'wife': 1784, 'kid': 1785, 'headache': 1789, 'quit': 1790, 'jazz': 1791, 'em': 1793, 'Ya': 1797, 'shopping': 1800, 'spree': 1801, 'TXT': 1802, 'custcare': 1803, 'grand': 1806, 'Gud': 1810, 'announcement': 1812, 'FREEPHONE': 1813, 'exhaust': 1814, 'train': 1815, 'pie': 1816, 'present': 1817, 'ar': 1818, 'swim': 1823, 'noon': 1826, 'Neva': 1835, 'imma': 1836, 'somethin': 1837, 'daily': 1838, 'valentine': 1839, 'game': 1840, 'future': 1845, 'beauty': 1847, 'aunty': 1848, 'shuhui': 1850, 'leona': 1851, 'family': 1853, 'happiness': 1854, 'snow': 1855, 'weather': 1856, 'grow': 1857, 'pub': 1862, 'bud': 1863, 'market': 1866, 'pop': 1868, 'Darren': 1869, 'Chat': 1871, 'area': 1872, 'postcode': 1874, 'Vodafone': 1875, 'forwarded': 1876, 'got': 1877, 'seven': 1879, 'Voucher': 1881, 'Holder': 1882, 'pc': 1883, 'funny': 1884, 'login': 1887, 'Dad': 1888, 'fetch': 1889, 'thanksgiving': 1891, 'effect': 1892, 'gorgeous': 1893, 'cartoon': 1902, 'eve': 1903, 'temple': 1904, 'church': 1905, 'email': 1907, 'gentle': 1909, 'Tuesday': 1913, 'town': 1915, 'bet': 1916, 'hella': 1917, 'drug': 1918, 'Sun': 1921, 'earth': 1922, 'evng': 1925, 'envelope': 1927, 'paper': 1928, 'prepare': 1930, 'study': 1931, 'ho': 1940, 'belly': 1941, 'laugh': 1942, 'TONE': 1944, 'STOP': 1945, 'peace': 1947, 'knw': 1948, 'awake': 1951, 'lonely': 1955, 'explain': 1957, 'xy': 1958, 'sex': 1961, 'bedroom': 1962, 'king': 1965, 'Baby': 1967, 'Great': 1968, 'an': 1978, 'torch': 1979, 'bold': 1980, 'urgent': 1981, 'farm': 1982, 'dad': 1983, 'sun': 1984, 'law': 1985, 'purchase': 1986, 'box': 1987, 'alex': 1991, 'gap': 1993, 'Mum': 1994, 'weird': 1998, 'idea': 1999, 'away': 2000, 'drivin': 2003, 'fantastic': 2004, 'N': 2005, 'alert': 2008, 'height': 2009, 'wer': 2013, 'Aftr': 2016, 'ws': 2017, 'student': 2018, 'Dey': 2019, 'Bt': 2020, 'stress': 2023, 'sell': 2025, 'assume': 2031, 'exactly': 2040, 'Dunno': 2042, 'low': 2047, 'spring': 2050, 'yay': 2051, 'tel': 2054, 'twice': 2055, 'tonite': 2057, 'add': 2058, 'rakhesh': 2060, 'Loyalty': 2061, 'TXTAUCTION': 2062, 'TC': 2063, 'Wish': 2065, 'mayb': 2066, 'rite': 2067, 'feeling': 2068, 'gal': 2069, 'glad': 2071, 'clock': 2072, 'shout': 2073, 'realise': 2074, 'eye': 2077, 'subscribe': 2078, 'Content': 2079, 'lip': 2086, 'library': 2088, 'holla': 2091, 'spare': 2092, 'possible': 2094, 'ac

In [29]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from collections import Counter
import re

# 1. Mock Data (Replace this with your SMS Spam Collection CSV file)
# data = [
#     ("Go jurong point, crazy.. Available only in bugis n great world la e buffet...", "ham"),
#     ("Ok lar... Joking wif u oni...", "ham"),
#     ("Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005.", "spam"),
#     ("U dun say so early hor... U c already then say...", "ham"),
#     ("FreeMsg Hey there darling it's been 3 week's now no word back!", "spam"),
#     ("WINNER!! As a valued network customer you have been selected to receivea £900 prize reward!", "spam"),
#     ("Had your mobile 11 months or more? U R entitled to Update to the latest colour mobiles with camera for Free!", "spam"),
#     ("I'm gonna be home soon and i don't want to talk about this stuff anymore tonight, k?", "ham"),
# ]

data = df
 

# 2. Text Preprocessing and Vocabulary Builder
def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-z0-9\s]', '', text)
    return text.split()

# Build Vocabulary
all_words = []
for text in data['text']:
    all_words.extend(clean_text(text))

word_counts = Counter(all_words)
# Filter words that appear at least once; add <PAD> and <UNK> tokens
vocab = {"<PAD>": 0, "<UNK>": 1}
for word in word_counts:
    if word not in vocab:
        vocab[word] = len(vocab)

VOCAB_SIZE = len(vocab)
MAX_LEN = 20  # Max sequence length for padding

print(vocab)

{'<PAD>': 0, '<UNK>': 1, 'go': 2, 'until': 3, 'jurong': 4, 'point': 5, 'crazy': 6, 'available': 7, 'only': 8, 'in': 9, 'bugis': 10, 'n': 11, 'great': 12, 'world': 13, 'la': 14, 'e': 15, 'buffet': 16, 'cine': 17, 'there': 18, 'got': 19, 'amore': 20, 'wat': 21, 'ok': 22, 'lar': 23, 'joking': 24, 'wif': 25, 'u': 26, 'oni': 27, 'free': 28, 'entry': 29, '2': 30, 'a': 31, 'wkly': 32, 'comp': 33, 'to': 34, 'win': 35, 'fa': 36, 'cup': 37, 'final': 38, 'tkts': 39, '21st': 40, 'may': 41, '2005': 42, 'text': 43, '87121': 44, 'receive': 45, 'questionstd': 46, 'txt': 47, 'ratetcs': 48, 'apply': 49, '08452810075over18s': 50, 'dun': 51, 'say': 52, 'so': 53, 'early': 54, 'hor': 55, 'c': 56, 'already': 57, 'then': 58, 'nah': 59, 'i': 60, 'dont': 61, 'think': 62, 'he': 63, 'goes': 64, 'usf': 65, 'lives': 66, 'around': 67, 'here': 68, 'though': 69, 'freemsg': 70, 'hey': 71, 'darling': 72, 'its': 73, 'been': 74, '3': 75, 'weeks': 76, 'now': 77, 'and': 78, 'no': 79, 'word': 80, 'back': 81, 'id': 82, 'like': 83, 'some': 84, 'fun': 85, 'you': 86, 'up': 87, 'for': 88, 'it': 89, 'still': 90, 'tb': 91, 'xxx': 92, 'std': 93, 'chgs': 94, 'send': 95, '150': 96, 'rcv': 97, 'even': 98, 'my': 99, 'brother': 100, 'is': 101, 'not': 102, 'speak': 103, 'with': 104, 'me': 105, 'they': 106, 'treat': 107, 'aids': 108, 'patent': 109, 'as': 110, 'per': 111, 'your': 112, 'request': 113, 'melle': 114, 'oru': 115, 'minnaminunginte': 116, 'nurungu': 117, 'vettam': 118, 'has': 119, 'set': 120, 'callertune': 121, 'all': 122, 'callers': 123, 'press': 124, '9': 125, 'copy': 126, 'friends': 127, 'winner': 128, 'valued': 129, 'network': 130, 'customer': 131, 'have': 132, 'selected': 133, 'receivea': 134, '900': 135, 'prize': 136, 'reward': 137, 'claim': 138, 'call': 139, '09061701461': 140, 'code': 141, 'kl341': 142, 'valid': 143, '12': 144, 'hours': 145, 'had': 146, 'mobile': 147, '11': 148, 'months': 149, 'or': 150, 'more': 151, 'r': 152, 'entitled': 153, 'update': 154, 'the': 155, 'latest': 156, 'colour': 157, 'mobiles': 158, 'camera': 159, 'co': 160, 'on': 161, '08002986030': 162, 'im': 163, 'gonna': 164, 'be': 165, 'home': 166, 'soon': 167, 'want': 168, 'talk': 169, 'about': 170, 'this': 171, 'stuff': 172, 'anymore': 173, 'tonight': 174, 'k': 175, 'ive': 176, 'cried': 177, 'enough': 178, 'today': 179, 'six': 180, 'chances': 181, 'cash': 182, 'from': 183, '100': 184, '20000': 185, 'pounds': 186, 'csh11': 187, '87575': 188, 'cost': 189, '150pday': 190, '6days': 191, '16': 192, 'tsandcs': 193, 'reply': 194, 'hl': 195, '4': 196, 'info': 197, 'urgent': 198, 'won': 199, '1': 200, 'week': 201, 'membership': 202, 'our': 203, '100000': 204, 'jackpot': 205, '81010': 206, 'tc': 207, 'wwwdbuknet': 208, 'lccltd': 209, 'pobox': 210, '4403ldnw1a7rw18': 211, 'searching': 212, 'right': 213, 'words': 214, 'thank': 215, 'breather': 216, 'promise': 217, 'wont': 218, 'take': 219, 'help': 220, 'granted': 221, 'will': 222, 'fulfil': 223, 'wonderful': 224, 'blessing': 225, 'at': 226, 'times': 227, 'date': 228, 'sunday': 229, 'xxxmobilemovieclub': 230, 'use': 231, 'credit': 232, 'click': 233, 'wap': 234, 'link': 235, 'next': 236, 'message': 237, 'httpwap': 238, 'xxxmobilemovieclubcomnqjkgighjjgcbl': 239, 'oh': 240, 'kim': 241, 'watching': 242, 'eh': 243, 'remember': 244, 'how': 245, 'spell': 246, 'his': 247, 'name': 248, 'yes': 249, 'did': 250, 'v': 251, 'naughty': 252, 'make': 253, 'wet': 254, 'fine': 255, 'if': 256, 'thats': 257, 'way': 258, 'feel': 259, 'gota': 260, 'b': 261, 'england': 262, 'macedonia': 263, 'miss': 264, 'goalsteam': 265, 'news': 266, 'ur': 267, 'national': 268, 'team': 269, '87077': 270, 'eg': 271, 'trywales': 272, 'scotland': 273, '4txt120': 274, 'poboxox36504w45wq': 275, 'that': 276, 'seriously': 277, 'going': 278, 'try': 279, 'ha': 280, 'pay': 281, 'first': 282, 'when': 283, 'da': 284, 'stock': 285, 'comin': 286, 'aft': 287, 'finish': 288, 'lunch': 289, 'str': 290, 'down': 291, 'lor': 292, 'ard': 293, 'smth': 294, 'ffffffffff': 295, 'alright': 296, 'can': 297, 'meet': 298, 'sooner': 299, 'just': 300, 'forced': 301, 'myself': 302, 'eat': 303, 'slice': 304, 'really': 305, 'hungry': 306, 'tho': 307, 'sucks': 308, 'mark': 309, 'getting': 310, 'worried': 311, 'knows': 312, 'sick': 313, 'turn': 314, 'pizza': 315, 'lol': 316, 'always': 317, 'convincing': 318, 'catch': 319, 'bus': 320, 'are': 321, 'frying': 322, 'an': 323, 'egg': 324, 'tea': 325, 'eating': 326, 'moms': 327, 'left': 328, 'over': 329, 'dinner': 330, 'do': 331, 'love': 332, 'amp': 333, 'were': 334, 'packing': 335, 'car': 336, 'ill': 337, 'let': 338, 'know': 339, 'theres': 340, 'room': 341, 'ahhh': 342, 'work': 343, 'vaguely': 344, 'what': 345, 'does': 346, 'wait': 347, 'clear': 348, 'sure': 349, 'being': 350, 'sarcastic': 351, 'why': 352, 'x': 353, 'doesnt': 354, 'live': 355, 'us': 356, 'yeah': 357, 'was': 358, 'apologetic': 359, 'fallen': 360, 'out': 361, 'she': 362, 'actin': 363, 'spoilt': 364, 'child': 365, 'caught': 366, 'till': 367, 'but': 368, 'we': 369, 'doing': 370, 'too': 371, 'badly': 372, 'cheers': 373, 'tell': 374, 'anything': 375, 'fear': 376, 'of': 377, 'fainting': 378, 'housework': 379, 'quick': 380, 'cuppa': 381, 'thanks': 382, 'subscription': 383, 'ringtone': 384, 'uk': 385, 'charged': 386, '5month': 387, 'please': 388, 'confirm': 389, 'by': 390, 'replying': 391, 'yup': 392, 'look': 393, 'timings': 394, 'msg': 395, 'again': 396, 'xuhui': 397, 'learn': 398, '2nd': 399, 'her': 400, 'lesson': 401, '8am': 402, 'oops': 403, 'roommates': 404, 'done': 405, 'see': 406, 'letter': 407, 'decide': 408, 'hello': 409, 'hows': 410, 'saturday': 411, 'texting': 412, 'youd': 413, 'decided': 414, 'tomo': 415, 'trying': 416, 'invite': 417, 'pls': 418, 'ahead': 419, 'watts': 420, 'wanted': 421, 'weekend': 422, 'abiola': 423, 'forget': 424, 'need': 425, 'crave': 426, 'most': 427, 'sweet': 428, 'arabian': 429, 'steed': 430, 'mmmmmm': 431, 'yummy': 432, '07732584351': 433, 'rodger': 434, 'burns': 435, 'tried': 436, 're': 437, 'sms': 438, 'nokia': 439, 'camcorder': 440, '08000930705': 441, 'delivery': 442, 'tomorrow': 443, 'who': 444, 'seeing': 445, 'hope': 446, 'man': 447, 'well': 448, 'endowed': 449, 'am': 450, 'ltgt': 451, 'inches': 452, 'callsmessagesmissed': 453, 'calls': 454, 'didnt': 455, 'get': 456, 'hep': 457, 'immunisation': 458, 'nigeria': 459, 'fair': 460, 'hopefully': 461, 'tyler': 462, 'cant': 463, 'could': 464, 'maybe': 465, 'ask': 466, 'bit': 467, 'stubborn': 468, 'hospital': 469, 'kept': 470, 'telling': 471, 'weak': 472, 'sucker': 473, 'hospitals': 474, 'suckers': 475, 'thinked': 476, 'time': 477, 'saw': 478, 'class': 479, 'gram': 480, 'usually': 481, 'runs': 482, 'half': 483, 'eighth': 484, 'smarter': 485, 'gets': 486, 'almost': 487, 'whole': 488, 'second': 489, 'fyi': 490, 'ride': 491, 'morning': 492, 'hes': 493, 'crashing': 494, 'place': 495, 'wow': 496, 'never': 497, 'realized': 498, 'embarassed': 499, 'accomodations': 500, 'thought': 501, 'liked': 502, 'since': 503, 'best': 504, 'seemed': 505, 'happy': 506, 'cave': 507, 'sorry': 508, 'give': 509, 'offered': 510, 'embarassing': 511, 'ac': 512, 'sptv': 513, 'new': 514, 'jersey': 515, 'devils': 516, 'detroit': 517, 'red': 518, 'wings': 519, 'play': 520, 'ice': 521, 'hockey': 522, 'correct': 523, 'incorrect': 524, 'end': 525, 'mallika': 526, 'sherawat': 527, 'yesterday': 528, 'find': 529, 'lturlgt': 530, 'congrats': 531, 'year': 532, 'special': 533, 'cinema': 534, 'pass': 535, 'yours': 536, '09061209465': 537, 'suprman': 538, 'matrix3': 539, 'starwars3': 540, 'etc': 541, 'bx420ip45we': 542, '150pm': 543, 'later': 544, 'meeting': 545, 'where': 546, 'reached': 547, 'yesgauti': 548, 'sehwag': 549, 'odi': 550, 'series': 551, 'pick': 552, 'burger': 553, 'yourself': 554, 'move': 555, 'pain': 556, 'killing': 557, 'good': 558, 'joke': 559, 'girls': 560, 'situation': 561, 'seekers': 562, 'part': 563, 'checking': 564, 'iq': 565, 'took': 566, 'forever': 567, 'come': 568, 'double': 569, 'check': 570, 'hair': 571, 'dresser': 572, 'said': 573, 'wun': 574, 'cut': 575, 'short': 576, 'nice': 577, 'pleased': 578, 'advise': 579, 'following': 580, 'recent': 581, 'review': 582, 'mob': 583, 'awarded': 584, '1500': 585, 'bonus': 586, '09066364589': 587, 'song': 588, 'dedicated': 589, 'day': 590, 'which': 591, 'dedicate': 592, 'valuable': 593, 'frnds': 594, 'rply': 595, 'complimentary': 596, 'trip': 597, 'eurodisinc': 598, 'trav': 599, 'acoentry41': 600, '1000': 601, 'dis': 602, '186150morefrmmob': 603, 'shracomorsglsuplt10': 604, 'ls1': 605, '3aj': 606, 'hear': 607, 'divorce': 608, 'barbie': 609, 'comes': 610, 'kens': 611, 'plane': 612, 'month': 613, 'wah': 614, 'lucky': 615, 'save': 616, 'money': 617, 'hee': 618, 'finished': 619, 'hi': 620, 'babe': 621, 'wanna': 622, 'something': 623, 'xx': 624, 'kkwhere': 625, 'youhow': 626, 'performed': 627, 'waiting': 628, 'machan': 629, 'once': 630, 'cool': 631, 'gentleman': 632, 'dignity': 633, 'respect': 634, 'peoples': 635, 'very': 636, 'much': 637, 'shy': 638, 'pa': 639, 'operate': 640, 'after': 641, 'same': 642, 'looking': 643, 'job': 644, 'tas': 645, 'earn': 646, 'ah': 647, 'stop': 648, 'urgnt': 649, 'real': 650, 'yo': 651, 'tickets': 652, 'one': 653, 'jacket': 654, 'used': 655, 'multis': 656, 'started': 657, 'requests': 658, 'came': 659, 'bed': 660, 'coins': 661, 'factory': 662, 'gotta': 663, 'nitros': 664, 'ela': 665, 'kanoil': 666, 'download': 667, 'wen': 668, 'stand': 669, 'close': 670, 'youll': 671, 'another': 672, 'night': 673, 'spent': 674, 'late': 675, 'afternoon': 676, 'casualty': 677, 'means': 678, 'havent': 679, 'any': 680, 'y': 681, 'stuff42moro': 682, 'includes': 683, 'sheets': 684, 'smile': 685, 'pleasure': 686, 'trouble': 687, 'pours': 688, 'rain': 689, 'sum1': 690, 'hurts': 691, 'becoz': 692, 'someone': 693, 'loves': 694, 'smiling': 695, 'service': 696, 'representative': 697, '0800': 698, '169': 699, '6031': 700, 'between': 701, '10am9pm': 702, 'guaranteed': 703, '5000': 704, 'planning': 705, 'buy': 706, 'lido': 707, '530': 708, 'show': 709, 'collected': 710, 'simply': 711, 'password': 712, 'mix': 713, '85069': 714, 'verify': 715, 'usher': 716, 'britney': 717, 'fml': 718, 'telugu': 719, 'moviewat': 720, 'abt': 721, 'loads': 722, 'loans': 723, 'wk': 724, 'hols': 725, 'run': 726, 'forgot': 727, 'hairdressers': 728, 'appointment': 729, 'four': 730, 'shower': 731, 'beforehand': 732, 'cause': 733, 'prob': 734, 'ham': 735, 'nothing': 736, 'else': 737, 'okay': 738, 'price': 739, 'long': 740, 'legal': 741, 'them': 742, 'ave': 743, 'ams': 744, 'gone': 745, '4the': 746, 'driving': 747, 'test': 748, 'yet': 749, 'youre': 750, 'mean': 751, 'guess': 752, 'gave': 753, 'boston': 754, 'men': 755, 'changed': 756, 'search': 757, 'location': 758, 'nyc': 759, 'cuz': 760, 'signin': 761, 'page': 762, 'says': 763, 'umma': 764, 'life': 765, 'vava': 766, 'lot': 767, 'dear': 768, 'wishes': 769, 'birthday': 770, 'making': 771, 'truly': 772, 'memorable': 773, 'aight': 774, 'hit': 775, 'would': 776, 'ip': 777, 'address': 778, 'considering': 779, 'computer': 780, 'isnt': 781, 'minecraft': 782, 'server': 783, 'grumpy': 784, 'old': 785, 'people': 786, 'mom': 787, 'better': 788, 'lying': 789, 'jokes': 790, 'worry': 791, 'busy': 792, 'plural': 793, 'noun': 794, 'research': 795, 'dinnermsg': 796, 'cos': 797, 'things': 798, 'scared': 799, 'mah': 800, 'loud': 801, 'gent': 802, 'contact': 803, 'last': 804, 'weekends': 805, 'draw': 806, 'shows': 807, '09064012160': 808, 'k52': 809, '12hrs': 810, '150ppm': 811, 'wa': 812, 'openin': 813, 'sentence': 814, 'formal': 815, 'anyway': 816, 'juz': 817, 'tt': 818, 'eatin': 819, 'puttin': 820, 'weighthaha': 821, 'anythin': 822, 'happened': 823, 'entered': 824, 'cabin': 825, 'bday': 826, 'boss': 827, 'felt': 828, 'askd': 829, 'invited': 830, 'apartment': 831, 'went': 832, 'specially': 833, 'holiday': 834, 'flights': 835, 'inc': 836, 'operator': 837, '0871277810910pmin': 838, '18': 839, 'goodo': 840, 'must': 841, 'friday': 842, 'eggpotato': 843, 'ratio': 844, 'tortilla': 845, 'needed': 846, 'hmmmy': 847, 'uncle': 848, 'informed': 849, 'paying': 850, 'school': 851, 'directly': 852, 'food': 853, 'private': 854, '2004': 855, 'account': 856, 'statement': 857, '07742676969': 858, '786': 859, 'unredeemed': 860, 'points': 861, '08719180248': 862, 'identifier': 863, '45239': 864, 'expires': 865, '2000': 866, 'caller': 867, '5903': 868, 'landline': 869, '09064019788': 870, 'box42wr29c': 871, 'applespairsall': 872, 'malarky': 873, 'todays': 874, 'voda': 875, 'numbers': 876, 'ending': 877, '7548': 878, '350': 879, 'award': 880, 'match': 881, '08712300220': 882, 'quoting': 883, '4041': 884, 'standard': 885, 'rates': 886, 'app': 887, 'sao': 888, 'mu': 889, 'predict': 890, 'll': 891, 'buying': 892, 'knowyetunde': 893, 'hasnt': 894, 'sent': 895, 'bother': 896, 'sending': 897, 'involve': 898, 'shouldnt': 899, 'imposed': 900, 'apologise': 901, 'girl': 902, 'del': 903, 'bak': 904, 'sum': 905, 'lucyxx': 906, 'kkhow': 907, 'tmorrowpls': 908, 'accomodate': 909, 'answer': 910, 'question': 911, 'sunshine': 912, 'quiz': 913, 'q': 914, 'top': 915, 'sony': 916, 'dvd': 917, 'player': 918, 'country': 919, 'algarve': 920, 'ansr': 921, '82277': 922, 'sptyrone': 923, 'laid': 924, 'dogging': 925, 'locations': 926, 'direct': 927, 'join': 928, 'uks': 929, 'largest': 930, 'bt': 931, 'txting': 932, 'gravel': 933, '69888': 934, 'nt': 935, 'ec2a': 936, '31pmsg150p': 937, 'haf': 938, 'msn': 939, 'yijuehotmailcom': 940, 'him': 941, 'rooms': 942, 'befor': 943, 'activities': 944, 'msgs': 945, 'chat': 946, 'svc': 947, 'hardcore': 948, 'services': 949, '69988': 950, 'age': 951, 'yr': 952, 'lazy': 953, 'type': 954, 'lect': 955, 'pouch': 956, 'sir': 957, 'mail': 958, 'swt': 959, 'nver': 960, 'tired': 961, 'little': 962, 'lovable': 963, 'persons': 964, 'cozsomtimes': 965, 'those': 966, 'occupy': 967, 'd': 968, 'biggest': 969, 'their': 970, 'hearts': 971, 'gud': 972, 'ni8': 973, 'open': 974, 'ya': 975, 'dot': 976, 'whats': 977, 'staff': 978, 'taking': 979, 'replied': 980, 'randy': 981, 'sexy': 982, 'female': 983, 'local': 984, 'luv': 985, 'netcollex': 986, 'ltd': 987, '08700621170150p': 988, 'ummmawill': 989, 'inour': 990, 'begin': 991, 'qatar': 992, 'pray': 993, 'hard': 994, 'ki': 995, 'deleted': 996, 'sindu': 997, 'birla': 998, 'soft': 999, 'wine': 1000, 'flowing': 1001, 'nevering': 1002, 'thk': 1003, 'plaza': 1004, 'typical': 1005, 'everywhere': 1006, 'dirt': 1007, 'floor': 1008, 'windows': 1009, 'shirt': 1010, 'sometimes': 1011, 'mouth': 1012, 'dream': 1013, 'without': 1014, 'chores': 1015, 'joy': 1016, 'lots': 1017, 'tv': 1018, 'exist': 1019, 'hail': 1020, 'mist': 1021, 'become': 1022, 'aaooooright': 1023, 'leaving': 1024, 'house': 1025, 'interview': 1026, 'boy': 1027, 'meare': 1028, 'missing': 1029, 'annoncement': 1030, 'years': 1031, '07046744435': 1032, 'arrange': 1033, '0871277810810': 1034, 'keep': 1035, 'safe': 1036, 'because': 1037, 'envy': 1038, 'everyone': 1039, 'sees': 1040, 'parentsi': 1041, 'hand': 1042, 'excited': 1043, 'each': 1044, 'spend': 1045, 'bootydelious': 1046, '32f': 1047, 'inviting': 1048, 'friend': 1049, 'yes434': 1050, 'no434': 1051, 'wwwsmsacubootydelious': 1052, 'frnd': 1053, '62468': 1054, 'bangbabes': 1055, 'order': 1056, 'should': 1057, 'content': 1058, 'goto': 1059, 'bangb': 1060, 'internetservice': 1061, 'menu': 1062, 'cultures': 1063, 'module': 1064, '09061701939': 1065, 's89': 1066, 'avoid': 1067, 'missunderstding': 1068, 'wit': 1069, 'beloved': 1070, 'ones': 1071, 'escape': 1072, 'fancy': 1073, 'bridge': 1074, 'needs': 1075, 'lager': 1076, 'completely': 1077, 'formclark': 1078, 'also': 1079, 'utter': 1080, 'waste': 1081, 'axis': 1082, 'bank': 1083, 'hmmm': 1084, 'hop': 1085, 'muz': 1086, 'discuss': 1087, 'liao': 1088, 'coming': 1089, 'bloody': 1090, 'hell': 1091, 'believe': 1092, 'surname': 1093, 'mr': 1094, 'clue': 1095, 'spanish': 1096, 'begins': 1097, 'm': 1098, 'bath': 1099, 'goodfine': 1100, 'youve': 1101, 'carlos': 1102, 'mall': 1103, 'turns': 1104, 'staying': 1105, 'til': 1106, 'smoke': 1107, 'worth': 1108, 'log': 1109, 'spoke': 1110, 'maneesha': 1111, 'wed': 1112, 'satisfied': 1113, 'experience': 1114, 'toll': 1115, 'lifted': 1116, 'hopes': 1117, 'offer': 1118, 'especially': 1119, 'approaches': 1120, 'studying': 1121, 'anyways': 1122, 'gr8': 1123, 'trust': 1124, 'guys': 1125, 'greatbye': 1126, 'handsome': 1127, 'finding': 1128, 'working': 1129, 'towards': 1130, 'net': 1131, 'mummy': 1132, 'wheres': 1133, 'boytoy': 1134, 'haha': 1135, 'awesome': 1136, 'minute': 1137, 'freephone': 1138, '0808': 1139, '145': 1140, '4742': 1141, '9am11pm': 1142, 'xmas': 1143, 'radio': 1144, 'jus': 1145, 'bathe': 1146, 'sis': 1147, 'using': 1148, 'finishes': 1149, 'unique': 1150, '30th': 1151, 'august': 1152, 'wwwareyouuniquecouk': 1153, 'joined': 1154, 'league': 1155, 'touch': 1156, 'deal': 1157, 'personal': 1158, 'finally': 1159, 'completed': 1160, 'course': 1161, 'itself': 1162, 'however': 1163, 'suggest': 1164, 'stays': 1165, 'able': 1166, 'ors': 1167, 'every': 1168, 'stool': 1169, 'settled': 1170, 'wishin': 1171, 'mrng': 1172, 'hav': 1173, 'story': 1174, 'hamster': 1175, 'dead': 1176, 'tmr': 1177, '1pm': 1178, 'orchard': 1179, 'mrt': 1180, 'kate': 1181, 'evening': 1182, 'babyjontet': 1183, 'found': 1184, 'enc': 1185, 'bucks': 1186, 'darlin': 1187, 'college': 1188, 'refilled': 1189, 'successfully': 1190, 'inr': 1191, 'ltdecimalgt': 1192, 'keralacircle': 1193, 'prepaid': 1194, 'balance': 1195, 'rs': 1196, 'transaction': 1197, 'kr': 1198, 'goodmorning': 1199, 'sleeping': 1200, 'ga': 1201, 'alter': 1202, 'dat': 1203, 'ericsson': 1204, 'oso': 1205, 'cannot': 1206, 'oredi': 1207, 'dats': 1208, 'straight': 1209, 'dogg': 1210, 'connection': 1211, 'before': 1212, 'refund': 1213, 'bill': 1214, 'both': 1215, 'shoot': 1216, 'big': 1217, 'ready': 1218, 'bruv': 1219, 'break': 1220, 'rewarding': 1221, 'semester': 1222, 'kkgoodstudy': 1223, 'noe': 1224, 'leh': 1225, 'sounds': 1226, 'heading': 1227, 'prediction': 1228, 'slept': 1229, 'past': 1230, 'few': 1231, 'nights': 1232, 'easy': 1233, 'ahsen': 1234, 'exam': 1235, 'march': 1236, 'gt': 1237, 'atm': 1238, 'register': 1239, 'os': 1240, 'called': 1241, 'ubandu': 1242, 'installing': 1243, 'diskyou': 1244, 'important': 1245, 'files': 1246, 'system': 1247, 'repair': 1248, 'shop': 1249, 'happen': 1250, 'romantic': 1251, 'nite': 1252, 'scenery': 1253, '500': 1254, '89545': 1255, 'collect': 1256, 'todayfrom': 1257, 'www4tcbiz': 1258, '2optout': 1259, '08718726270150gbpmtmsg18': 1260, 'appreciate': 1261, 'partner': 1262, 'career': 1263, 'off': 1264, 'flyng': 1265, 'start': 1266, 'horo': 1267, 'followed': 1268, 'star': 1269, 'sign': 1270, 'g': 1271, 'aries': 1272, 'company': 1273, 'elama': 1274, 'po': 1275, 'mudyadhu': 1276, 'strict': 1277, 'than': 1278, 'teacher': 1279, 'bcoz': 1280, 'teaches': 1281, 'conducts': 1282, 'lessons': 1283, 'gandhipuram': 1284, 'walk': 1285, 'cross': 1286, 'road': 1287, 'side': 1288, 'street': 1289, 'rubber': 1290, 'battery': 1291, 'died': 1292, 'yeshere': 1293, 'flirt': 1294, '10p': 1295, 'sam': 1296, '25': 1297, 'recdthirtyeight': 1298, 'pence': 1299, 'printed': 1300, 'upstairs': 1301, 'closer': 1302, 'youwhen': 1303, 'wil': 1304, 'reach': 1305, 'theory': 1306, 'argument': 1307, 'wins': 1308, 'loses': 1309, 'person': 1310, 'argue': 1311, 'kick': 1312, '447801259231': 1313, 'secret': 1314, 'admirer': 1315, 'ufind': 1316, 'rreveal': 1317, 'thinks': 1318, 'specialcall': 1319, '09058094597': 1320, 'tomarrow': 1321, 'hearing': 1322, 'laptop': 1323, 'case': 1324, 'pleassssssseeeeee': 1325, 'tel': 1326, 'avent': 1327, 'sportsx': 1328, 'shining': 1329, 'meant': 1330, 'signing': 1331, 'although': 1332, 'told': 1333, 'into': 1334, 'baig': 1335, 'face': 1336, 'watches': 1337, 'watch': 1338, 'fr': 1339, 'thanx': 1340, 'everything': 1341, 'uve': 1342, 'touched': 1343, 'commercial': 1344, 'website': 1345, 'slippers': 1346, 'asked': 1347, 'kallis': 1348, 'bat': 1349, 'innings': 1350, 'goodnight': 1351, 'fix': 1352, 'wake': 1353, 'dearly': 1354, 'missed': 1355, 'sleep': 1356, 'congratulations': 1357, 'cd': 1358, 'vouchers': 1359, '125gift': 1360, 'music': 1361, '87066': 1362, 'tncs'

In [30]:
# 3. Custom PyTorch Dataset
class SMSDataset(Dataset):
    def __init__(self, data, vocab, max_len):
        self.data = data['text']
        self.labels = data['label']
        self.vocab = vocab
        self.max_len = max_len
        self.labels_map = {"ham": 0, "spam": 1}

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        text = self.data[idx]
        label = self.labels[idx]
        words = clean_text(text)
        
        # Numericalize text (Word -> ID)
        encoded = [self.vocab.get(word, self.vocab["<UNK>"]) for word in words]
        
        # Pad or truncate sequence to fixed length
        if len(encoded) < self.max_len:
            encoded += [self.vocab["<PAD>"]] * (self.max_len - len(encoded))
        else:
            encoded = encoded[:self.max_len]
            
        return torch.tensor(encoded, dtype=torch.long), torch.tensor(self.labels_map[label], dtype=torch.float)

# Create Dataset and DataLoader
dataset = SMSDataset(data, vocab, MAX_LEN)
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [31]:
# 4. Simple RNN Classification Model
class SpamClassifier(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim):
        super(SpamClassifier, self).__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim, padding_idx=0)
        self.lstm = nn.LSTM(embedding_dim, hidden_dim, batch_first=True)
        self.fc = nn.Linear(hidden_dim, 1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, x):
        # x shape: [batch_size, max_len]
        embedded = self.embedding(x) # [batch_size, max_len, embedding_dim]
        lstm_out, (hidden, cell) = self.lstm(embedded) # hidden shape: [1, batch_size, hidden_dim]
        
        # Use the final hidden state of the LSTM
        last_hidden = hidden.squeeze(0) # [batch_size, hidden_dim]
        out = self.fc(last_hidden) # [batch_size, 1]
        return self.sigmoid(out)

# Hyperparameters
EMBEDDING_DIM = 32
HIDDEN_DIM = 16

model = SpamClassifier(VOCAB_SIZE, EMBEDDING_DIM, HIDDEN_DIM)
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

# 5. Training Loop
print("Starting Training...")
model.train()
for epoch in range(5):
    epoch_loss = 0
    for texts, labels in dataloader:
        optimizer.zero_grad()
        
        predictions = model(texts).squeeze(1) # shape matches labels [batch_size]
        loss = criterion(predictions, labels)
        
        loss.backward()
        optimizer.step()
        
        epoch_loss += loss.item()
        
    print(f"Epoch {epoch+1} | Loss: {epoch_loss / len(dataloader):.4f}")

# 6. Inference Example
def predict(text):
    model.eval()
    with torch.no_grad():
        words = clean_text(text)
        encoded = [vocab.get(word, vocab["<UNK>"]) for word in words]
        if len(encoded) < MAX_LEN:
            encoded += [vocab["<PAD>"]] * (MAX_LEN - len(encoded))
        else:
            encoded = encoded[:MAX_LEN]
            
        test_tensor = torch.tensor([encoded], dtype=torch.long)
        prediction = model(test_tensor).item()
        return "Spam" if prediction > 0.5 else "Ham"

print("\nTesting Predictions:")
print(f"'Free entry to win cash now!' -> {predict('Free entry to win cash now!')}")
print(f"'Hey, are we still meeting for lunch?' -> {predict('Hey, are we still meeting for lunch?')}")

Starting Training...
Epoch 1 | Loss: 0.1690
Epoch 2 | Loss: 0.0685
Epoch 3 | Loss: 0.0317
Epoch 4 | Loss: 0.0181
Epoch 5 | Loss: 0.0167

Testing Predictions:
'Free entry to win cash now!' -> Spam
'Hey, are we still meeting for lunch?' -> Ham