In [1]:
import mlflow


mlflow.set_tracking_uri("sqlite:///mlflow.db")
mlflow.set_experiment("spam-experiment")

<Experiment: artifact_location='/mnt/c/Users/user/Documents/Projects/mlops-exer-1/notebooks/mlruns/1', creation_time=1780963326545, effective_trace_archival_retention=None, experiment_id='1', last_update_time=1780963326545, lifecycle_stage='active', name='spam-experiment', tags={}, trace_location=None, workspace='default'>

In [2]:
# from spam_checker.data.spam_data_module import SPAMDataModule

In [3]:
# spam_data = SPAMDataModule()

In [4]:
# spam_data.prepare_data()

In [5]:
import pandas as pd

# Paste your copied file path inside the quotes
# df = pd.read_csv('../test_dataset/spam.csv')

df = pd.read_csv('../test_dataset/spam.csv', encoding_errors='ignore')

df = df[['v1', 'v2']]

# df['v1'] = df['v1'].replace('spam', '1')
# df['v1'] = df['v1'].replace('ham', '0')

# View the first few rows of your data
df.head(10)

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...
5  spam  FreeMsg Hey there darling it's been 3 week's n...
6   ham  Even my brother is not like to speak with me. ...
7   ham  As per your request 'Melle Melle (Oru Minnamin...
8  spam  WINNER!! As a valued network customer you have...
9  spam  Had your mobile 11 months or more? U R entitle...

In [6]:
df['v1'] = df['v1'].replace('spam', '1')
df['v1'] = df['v1'].replace('ham', '0')

# View the first few rows of your data
df.head(10)

  v1                                                 v2
0  0  Go until jurong point, crazy.. Available only ...
1  0                      Ok lar... Joking wif u oni...
2  1  Free entry in 2 a wkly comp to win FA Cup fina...
3  0  U dun say so early hor... U c already then say...
4  0  Nah I don't think he goes to usf, he lives aro...
5  1  FreeMsg Hey there darling it's been 3 week's n...
6  0  Even my brother is not like to speak with me. ...
7  0  As per your request 'Melle Melle (Oru Minnamin...
8  1  WINNER!! As a valued network customer you have...
9  1  Had your mobile 11 months or more? U R entitle...